apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  root-password: c2VjcmV0MTIzLg==
  user-password: c2VjcmV0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  database_name: my_db
  database_user: edcilo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
          - containerPort: 3306
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: root-password
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mariadb-configmap
                key: database_name
          - name: MARIADB_USER
            valueFrom:
              configMapKeyRef:
                name: mariadb-configmap
                key: database_user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: user-password

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
